version: '3.9'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_USER: users
      POSTGRES_PASSWORD: password
      POSTGRES_DB: it_lab
      DB_HOST: db
      DB_PORT: 5432
      REDIS_HOST: redis
    restart: always

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: users
      POSTGRES_PASSWORD: password
      POSTGRES_DB: it_lab
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U users -d it_lab"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:5
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: